# Usa imagem oficial do Node.js
FROM node:20

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos de dependência
COPY package*.json ./

# Instala as dependências do projeto
RUN npm install

# Copia o restante da aplicação
COPY . .

# Expõe a porta da API
EXPOSE 3000

# Comando padrão
CMD ["npm", "run", "dev"]